import './globals.css'
import {IBM_Plex_Mono, Figtree} from "next/font/google"

const mono = IBM_Plex_Mono({weight: "300", subsets: ["latin"]});
const poly = Figtree({weight: "variable", subsets: ["latin"]})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${mono} ${poly}`}>{children}</body>
    </html>
  )
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
